[profile.default]
solc_version = "0.8.17"
auto_detect_solc = false
optimizer_runs = 9_999_999
via_ir = true

remappings = [
  "@std=lib/forge-std/src/",
  "@base=lib/solbase/",
  "@keep=lib/keep/src/",
  "@rage=lib/rage-router/src"
]

[fuzz]
runs = 1_000

[profile.fuzz.ci]
runs = 100_000

